.TH ID3CONVERT 1 "May 2000" local "User Command"
.SH NAME
id3convert \- Converts between id3v1 and id3v2 tags of an mp3 file.
.SH SYNOPSIS
.B id3convert
.RB [
.I OPTION
.RB ]
.RB [
.I FILE
.RB ]
.br
.SH DESCRIPTION
.B Id3convert
converts between id3v1 and id3v2 tags of an mp3 file. Id3convert will render
both types of tag by default. Only the last tag type indicated in the option
list will be used. Non-rendered tags will remain unchanged in the original
file. Id3convert will also parse and convert Lyrics3 v2.0 frames, but will
not render them.

.SH OPTIONS
.TP
.B \-1, \-\-v1tag
Render only the id3v1 tag
.TP
.B \-2, \-\-v2tag
Render only the id3v2 tag
.TP
.B \-s, \-\-strip
Strip, rather than render, the tags
.TP
.B \-p, \-\-padding
Use padding in the tag
.TP
.B \-h, \-\-help
Display help and exit
.TP
.B \-v, \-\-version
Display version information and exit

.SH SEE ALSO
id3tag(1), id3info(1), id3v2(1)
.SH AUTHOR
.B id3lib
was originally designed and implemented by Dirk Mahoney and is
maintained by Scott Thomas Haug <sth2@cs.wustl.edu>. Manual page written for
Debian GNU/Linux by Robert Woodcock <rcw@debian.org>.
