.TH ID3CP 1 "July 2001" local "User Command"
.SH NAME
id3cp \- Copies tags from one file to another.
.SH SYNOPSIS
.B id3cp
.RB [
.I OPTION
.RB ] ...
.RB [
.I SOURCE
.RB ]
.RB [
.I DEST
.RB ]
.br
.SH DESCRIPTION
.B Id3cp
copies tags from SOURCE to DEST.
.SH OPTIONS
.TP
.B \-1, \-\-v1tag
Render only the id3v1 tag
.TP
.B \-2, \-\-v2tag
Render only the id3v2 tag
.TP
.B \-h, \-\-help
Display help and exit
.TP
.B \-v, \-\-version
Display version information and exit
.SH SEE ALSO
id3convert(1), id3info(1), id3v2(1)
.SH AUTHOR
.B id3lib
was originally designed and implemented by Dirk Mahoney and is
maintained by Scott Thomas Haug <sth2@cs.wustl.edu>. Manual page written for
Debian GNU/Linux by Robert Woodcock <rcw@debian.org>.
