.TH ID3INFO 1 "May 2000" local "User Command"
.SH NAME
id3info \- Display id3 tag information.
.SH SYNOPSIS
.B id3info
.RB [
.I OPTION
.RB ]
.RB [
.I FILE
.RB ]
.br
.SH DESCRIPTION
.B Id3info
displays both the id3v1 and id3v2 tag information for a file.
Id3info will not differentiate between the two types of tags.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display help and exit
.TP
.B \-v, \-\-version
Display version information and exit
.SH SEE ALSO
id3convert(1), id3tag(1), id3v2(1)
.SH AUTHOR
.B id3lib
was originally designed and implemented by Dirk Mahoney and is
maintained by Scott Thomas Haug <sth2@cs.wustl.edu>. Manual page written for
Debian GNU/Linux by Robert Woodcock <rcw@debian.org>.

